// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchoolPortal.Common.Models.dboSchema
{
    public partial class sp_GetCountryByIdResult
    {
        public Guid Id { get; set; }
        [StringLength(100)]
        public string CountryName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        [StringLength(10)]
        public string Status { get; set; }
        [StringLength(250)]
        public string StatusMessage { get; set; }
    }
}
