// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SchoolPortal.Common.Models;
using SchoolPortal.Common.Models.dboSchema;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SchoolPortal.Common.Models
{
    public partial interface ISchoolPortalContextProcedures
    {
        Task<int> sp_DeleteCountryMasterAsync(Guid? id, Guid? modifiedBy, DateTime? modifiedDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetAllCountriesResult>> sp_GetAllCountriesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetAllCountries_PagedResult>> sp_GetAllCountries_PagedAsync(int? pageNumber, int? pageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetCountryByIdResult>> sp_GetCountryByIdAsync(Guid? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertCountryMasterAsync(Guid? id, string countryName, bool? isActive, bool? isDeleted, Guid? createdBy, DateTime? createdDate, Guid? modifiedBy, DateTime? modifiedDate, string status, string statusMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_UpdateCountryMasterAsync(Guid? id, string countryName, bool? isActive, bool? isDeleted, Guid? modifiedBy, DateTime? modifiedDate, string status, string statusMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
