// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SchoolPortal.Common.Models;
using SchoolPortal.Common.Models.dboSchema;
using System;
using System.Collections.Generic;

namespace SchoolPortal.Common.Models.Configurations
{
    public partial class CityMasterConfiguration : IEntityTypeConfiguration<CityMaster>
    {
        public void Configure(EntityTypeBuilder<CityMaster> entity)
        {
            entity.HasKey(e => e.Id).HasName("PKCityMaster");

            entity.Property(e => e.Id).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CityMaster> entity);
    }
}
