// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SchoolPortal.Common.Models;
using SchoolPortal.Common.Models.dboSchema;
using System;
using System.Collections.Generic;

namespace SchoolPortal.Common.Models.Configurations
{
    public partial class HolidayClassDetailConfiguration : IEntityTypeConfiguration<HolidayClassDetail>
    {
        public void Configure(EntityTypeBuilder<HolidayClassDetail> entity)
        {
            entity.HasKey(e => new { e.Id, e.ClassMasterId, e.SectionMasterId }).HasName("PK_HolidayClassDetails_1");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Status).HasDefaultValue("INC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HolidayClassDetail> entity);
    }
}
